[book]
authors = ["Oliver Nordbjerg"]
language = "zh"
multilingual = false
src = "translations/zh"
title = "Foundry Book"
description = "A book on all things Foundry"

[build]
create-missing = false

[preprocessor.external-links]

[output.html]
no-section-label = true
git-repository-icon = "fa-github"
site-url = "/docs/foundry/"
git-repository-url = "https://github.com/lbc-team/foundry-book-in-chinese"
edit-url-template = "https://github.com/lbc-team/foundry-book-in-chinese/tree/feature-zh/{path}"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]
cname = "https://learnblockchain.cn/docs/foundry/i18n/zh/"
additional-css = ["src/static/custom.css"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

[[output.i18n.translations.zh]]
language = "zh"
translators = ["https://www.github.com/coldstar1993", "https://github.com/xilibi2003"]
title = "Foundry 中文文档"
